### PR TITLE
feat(auth): add desktop size to auth-success-card.tsx

### PR DESCRIPTION
**Pull request by xdjeremy**

### CODE REVIEW

**Review by tamrivera05 — APPROVED** [review]
<3

**Review by tamrivera05 — CHANGES_REQUESTED** [review]
merge conflict hmp hmp

**Comment by tamrivera05** [comment]
### Merge activity

* **Apr 29, 2:26 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/TamJer/maiserve/45) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Comment by xdjeremy** [comment]
ok na

**Pull request merged**
